Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Entity\Covoiturage;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['Email'])]
#[UniqueEntity(fields: ['Email'], message: 'There is already an account with this Email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'integer')]
    private ?int $credit = 20;

    #[ORM\Column(length: 180)]
    private ?string $Email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private $photo = null;



    /**
     * @var Collection<int, Covoiturage>
     */
    #[ORM\ManyToMany(targetEntity: Covoiturage::class, inversedBy: 'passagers', cascade: ['persist'])]
    private Collection $covoiturages;

    /**
     * @var Collection<int, Voiture>
     */
    #[ORM\OneToMany(targetEntity: Voiture::class, mappedBy: 'proprietaire', cascade: ['persist'])]
    private Collection $voitures;

    /**
     * @var Collection<int, Avis>
     */
    #[ORM\OneToMany(targetEntity: Avis::class, mappedBy: 'auteur', cascade: ['persist'])]
    private Collection $avis;

    public function __construct()
    {
        $this->covoiturages = new ArrayCollection();
        $this->voitures = new ArrayCollection();
        $this->avis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->Email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    //role admin 

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function eraseCredentials(): void
    {
        // Clear temporary sensitive data here if needed
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, Covoiturage>
     */
    public function getCovoiturages(): Collection
    {
        return $this->covoiturages;
    }

    public function addCovoiturage(Covoiturage $covoiturage): static
    {
        if (!$this->covoiturages->contains($covoiturage)) {
            $this->covoiturages->add($covoiturage);
        }

        return $this;
    }

    public function removeCovoiturage(Covoiturage $covoiturage): static
    {
        $this->covoiturages->removeElement($covoiturage);

        return $this;
    }

    /**
     * @return Collection<int, Voiture>
     */
    public function getVoitures(): Collection
    {
        return $this->voitures;
    }

    public function addVoiture(Voiture $voiture): static
    {
        if (!$this->voitures->contains($voiture)) {
            $this->voitures->add($voiture);
            $voiture->setProprietaire($this);
        }

        return $this;
    }

    public function removeVoiture(Voiture $voiture): static
    {
        if ($this->voitures->removeElement($voiture)) {
            if ($voiture->getProprietaire() === $this) {
                $voiture->setProprietaire(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setAuteur($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        if ($this->avis->removeElement($avi)) {
            if ($avi->getAuteur() === $this) {
                $avi->setAuteur(null);
            }
        }

        return $this;
    }

    #[ORM\Column(type: 'boolean')]
    private bool $marqueCreee = false;

    public function isMarqueCreee(): bool
    {
        return $this->marqueCreee;
    }

    public function setMarqueCreee(bool $val): self
    {
        $this->marqueCreee = $val;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getPseudo() ?: 'Utilisateur sans pseudo';
    }

    public function getCredit(): ?int
    {
        return $this->credit;
    }
    public function setCredit(int $credit): self
    {
        $this->credit = $credit;

        return $this;
    }

}

src/Form/MonCompteForm.php
<?php
namespace App\Form;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class MonCompteForm extends AbstractType
{
    function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('telephone', NumberType::class, [
                'label' => 'Téléphone',
                'attr' => ['class' => 'form-control'],
                'required' => true,
            ])
            ->add('adresse', TextType::class, [
                'label' => 'Adresse',
                'attr' => ['class' => 'form-control '],

                'required' => true,
            ])
            ->add('pseudo', TextType::class, [
                'label' => 'Pseudo',
                'attr' => ['class' => 'form-control'],
                'required' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/MonCompteController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Covoiturage;
use App\Entity\MonCompte;
use App\Entity\MonCompteRepository;
use App\Entity\User;
use App\Form\UserForm;
use App\Repository\CovoiturageRepository;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Form\UserType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;


final class MonCompteController extends AbstractController
{
    #[Route('/compte', name: 'app_compte')]
    public function Inforpersonel(): Response
    {

        return $this->render('mon_compte/inforpersonnel.html.twig', [
            'info' => 'informationpersonel',
        ]);
    }


    #[Route('/compte/information', name: 'app_mon_compte_informationpersonnel')]
    public function index(UserRepository $userRepository, Request $request): Response
    {
        //$Compte = $userRepository->findAll();
        $user = $this->getUser();
        if (!$user) {
            throw $this->createAccessDeniedException('Vous devez être connecté pour accéder à cette page.');
        }
        $referer = $request->headers->get('referer');
        return $this->render('mon_compte/index.html.twig', [
            'monCompte' => [$user], // On l'encapsule dans un tableau pour garder le "for" dans Twig
            'backUrl' => $referer ?? $this->generateUrl('app_compte'),
        ]);
    }

    #[Route('/compte/covoiturage', name: 'app_mon_compte_covoiturage')]
    public function covoiturage(CovoiturageRepository $covoiturageRepository): Response
    {
        $CompteCovoiturage = $covoiturageRepository->findAll();
        return $this->render('mon_compte/covoiturage.html.twig', [
            'comptecovoiturage' => $CompteCovoiturage,
        ]);
    }

    #[Route('/compte/information', name: 'app_mon_compte_information')]
    public function information(): Response
    {

        return $this->render('mon_compte/information.html.twig', [
        ]);
    }
    #[Route('/compte/newcomplement', name: 'app_mon_compte_information_compteinformation')]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $user = $this->getUser(); // récupère l'utilisateur connecté
        if (!$user) {
            throw $this->createAccessDeniedException();
        }

        $form = $this->createForm(MonCompteForm::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush(); // pas besoin de persist() car c’est un objet existant
            $this->addFlash('success', 'Informations mises à jour.');
            return $this->redirectToRoute('app_mon_compte_information');
        }

        return $this->render('mon_compte/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

}

templates/mon_compte/covoiturage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Covoiturage{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Covoiturage</h1>
    <p class="text-center">Bienvenue dans la section Covoiturage de votre compte.</p>

    {% if covoiturages is empty %}
        <div class="alert alert-info text-center">Aucun covoiturage trouvé.</div>
    {% else %}
        <div class="row">
            {% for covoiturage in covoiturages %}
                <div class="col-12 mb-3">
                    <div class="card shadow-sm">
                        <div class="card-body">

                            <div class="d-flex align-items-center mb-2">
                                <img src="{{ asset('uploads/photos/' ~ covoiturage.user.photo) }}" alt="photo de {{ covoiturage.user.pseudo }}" width="60" height="60" class="rounded-circle me-3">
                                <strong>{{ covoiturage.user.pseudo ?? 'non renseigné' }}</strong>
                            </div>

                            <p class="card-text">
                                {% if covoiturage.nbplace > 0 %}
                                    <i class="bi bi-person"></i> {{ covoiturage.nbplace }} 
                                    place{% if covoiturage.nbplace > 1 %}s{% endif %} restante{% if covoiturage.nbplace > 1 %}s{% endif %}
                                {% else %}
                                    <span class="text-danger fw-bold"><i class="bi bi-x-circle"></i> Complet</span>
                                {% endif %}
                            </p>

                            <p class="card-title">
                                <strong>{{ covoiturage.lieudepart }} → {{ covoiturage.lieuarrivee }}</strong>
                                {% if covoiturage.voiture and covoiturage.voiture.type == 'Electrique' %}
                                    <span class="badge bg-success">🌱 Écologique</span>
                                {% endif %}
                            </p>

                            <p class="card-subtitle mb-2 text-muted">
                                Départ le <strong>{{ covoiturage.dateDepart|date('d/m/Y') }}</strong>
                            </p>

                            <p class="card-text">
                                <strong>Prix par personne :</strong> {{ covoiturage.prixpersonne }} €
                            </p>

                            {# Bouton Détails #}
                            <button class="btn btn-info btn-sm" data-bs-toggle="collapse" data-bs-target="#details-{{ covoiturage.id }}" aria-expanded="false" aria-controls="details-{{ covoiturage.id }}">
                                Détails
                            </button>

                            {# Détails masqués #}
                            <div class="collapse mt-2" id="details-{{ covoiturage.id }}">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                        <strong>Véhicule :</strong>
                                        {{ covoiturage.voiture?.marque ?? 'Non précisée' }} {{ covoiturage.voiture?.modele ?? '' }}
                                    </li>
                                    <li class="list-group-item">
                                        <strong>Type :</strong>
                                        {{ covoiturage.voiture?.type ?? 'Non précisé' }}
                                    </li>
                                    <li class="list-group-item">
                                        <strong>Heure de départ :</strong> {{ covoiturage.dateDepart|date('H:i') }}
                                    </li>
                                    <li class="list-group-item">
                                        <strong>Statut :</strong> {{ covoiturage.statut }}
                                    </li>
                                    <li class="list-group-item">
                                        <strong>Description :</strong> {{ covoiturage.description ?? 'Aucune description' }}
                                    </li>
                                </ul>
                            </div>

                            {# Réservation possible #}
                            {% if covoiturage.nbplace >= 3 and app.user %}
                                <form action="{{ path('app_covoiturage_reserver', {'id': covoiturage.id}) }}" method="post" class="d-inline mt-2">
                                    <input type="hidden" name="_token" value="{{ csrf_token('covoiturage_reserver' ~ covoiturage.id) }}">
                                    <button class="btn btn-primary btn-sm">Réserver</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}

templates/mon_compte/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}listes des information personnelles{% endblock %}


{% block body %}
<a href="{{ path('app_compte') }}" class="btn btn-outline-success mb-4">
  &larr; Retour
</a>


    <div class="container-fluid mt-5 mb-5">
        <div class="row justify-content-center text-center">

        <p class="lead">Voici les informations de votre compte</p>

            <div class="col-md-12">
                <h2>Informations personnelles</h2>  
            {% for compte in monCompte %}

                    <p>{{ compte.nom }} {{ compte.prenom }}</p>
                    <p>{{ compte.email }}</p>
                    <p>{{ compte.telephone }}</p>
                    <p>{{ compte.adresse }}</p>
                    <p>{{ compte.pseudo }}</p>
                     {% if compte.photo %}
                    <p><strong>Crédit disponible :</strong> {{ compte.credit }} jeton</p>
                     <p><strong>Photo de profil :</strong></p>
                  <img src="{{ asset('uploads/photos/' ~ compte.photo) }}" alt="Photo de profil" class="img-thumbnail" width="150">
                   {% else %}
                  <p><strong>Photo de profil :</strong> Non renseignée</p>
                   {% endif %}
                    <p><a href="{{ path('app_mon_compte_information_compteinformation') }}">Modifier les informations</a></p>
                    
                  {% endfor %}
        </div>
    </div>
    </div>

{% endblock %}

templates/mon_compte/information.html.twig
{% extends 'base.html.twig' %}
{% block title %}Information{% endblock %}
{% block body %}
<a href="{{ path('app_mon_compte_edit') }}" class="btn btn-primary mb-4">  ◀️ </a>
<div class="container text-center ">
    <h1>Information</h1>
    <p>veuillez trouver ci-dessous les informations de votre compte.</p>
<div class="row">
    <div class="col-md-12 text-center">
       <p>telephone:0123456789</p>
       <p>email:Ecorideoutlook.com</p>
       <p>adresse: 123 rue de l'Ecoride, 75000 Paris</p>
       <p>horaires d'ouverture: Lundi - Vendredi, 9h - 18h</p>
       <p>contact personnel:0612345678</p>
    </div>    
</div>
{% endblock %} 

templates/mon_compte/inforpersonnel.html.twig
{% extends 'base.html.twig' %}
{% block title %}Espace Utilisateurs{% endblock %}
{% block body %}
<div class="container-fluid mt-5 mb-5"> 
  <div class="row">
    <div class="col-md-12">
      <h1>Espace Utilisateurs</h1>
    <div class="row justify-content-center shadow p-3 mb-5 shadow">
    <a href="{{ path('app_mon_compte_informationpersonnel') }}" class="btn btn-secondary mb-4 ">Information Personnel</a>
        <a href="{{ path('app_covoiturage') }}" class="btn btn-secondary mb-3"> les covoiturages disponibles</a>
        <a href="{{ path('app_marque_new') }}" class="btn btn-secondary mb-3 ">Ajouter un covoiturage</a>
    <a href="{{ path('app_mes_reservations') }}" class="btn btn-secondary mb-3">Mes réservations</a>
        <a href="{{ path('app_voiture') }}" class="btn btn-secondary mb-3 form-control">Ma Voiture</a>
            <a href="{{ path('app_covoiturage_historique') }}" class="btn btn-secondary mb-4 ">Historique covoiturage</a>

    <a href="{{ path('app_register_delete') }}" class="btn btn-danger mb-3  form-control">Supprimer mon compte</a> </div>
      <a href="{{ path('app_accueil') }}" class="btn btn-primary">Retour à l'accueil</a>


    </div>
  </div>
{% endblock %}

templates/mon_compte/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Compte{% endblock %}

{% block body %}

 <div class="container-fluid mt-5 bg-light p-5">

 {% if app.user %}
    <p>Bienvenue, {{ app.user.nom }} {{ app.user.prenom }}!</p>
    <p>Vous pouvez ajouter les informations manquantes ci-dessous.</p>
    {{ form_start(form) }}
        {{ form_row(form.telephone, {'attr': {'class': 'form-control'}}) }}
        {{ form_row(form.adresse, {'attr': {'class': 'form-control'}}) }}
        {{ form_row(form.pseudo, {'attr': {'class': 'form-control'}}) }}


        <button class="btn btn-primary">Enregistrer</button>
    {{ form_end(form) }}
    <p><a href="{{ path('app_mon_compte_information') }}">Retour à la page d'information du compte</a></p>
    {% else %}
    <h1>Accès refusé</h1>
    <p>Vous devez être connecté pour accéder à cette page.</p>
    {% endif %}
 </div>

{% endblock %}

templates/mon_compte/photo1.html.twig
{# templates/mon_compte/photo1.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}ajouter une photo{% endblock %}

{% block body  %}
   <div class="container  d-flex justify-content-end ">
        <form method="post" enctype="multipart/form-data">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary">Ajouter ta photo</button>
            {{ form_end(form) }}
        </form>

    </div>  
{% endblock %}